// Vollständige, erweiterte Fragensammlung für das Family Quizzz
const allQuestions = [
    // ==========================================
    // KATEGORIE: KLASSE 2 (100 FRAGEN)
    // ==========================================
    
    // --- MATHE 2. KLASSE (IDs 2001 - 2050) ---
    { id: 2001, level: 1, category: "klasse2", question: "Rechne aus: Was ist 25 + 14?", answers: ["35", "38", "39", "40"], correct: 2 },
    { id: 2002, level: 1, category: "klasse2", question: "Was ist das Doppelte von 8?", answers: ["12", "14", "16", "18"], correct: 2 },
    { id: 2003, level: 1, category: "klasse2", question: "Rechne aus: Was ist 45 - 20?", answers: ["15", "25", "35", "45"], correct: 1 },
    { id: 2004, level: 1, category: "klasse2", question: "Was ergibt die Malaufgabe 2 * 5?", answers: ["7", "8", "10", "12"], correct: 2 },
    { id: 2005, level: 1, category: "klasse2", question: "Was ist die Hälfte von 20?", answers: ["5", "10", "15", "20"], correct: 1 },
    { id: 2006, level: 1, category: "klasse2", question: "Rechne aus: 3 * 3 = ?", answers: ["6", "8", "9", "12"], correct: 2 },
    { id: 2007, level: 1, category: "klasse2", question: "Welche Zahl fehlt hier: 10, 20, 30, __, 50?", answers: ["35", "40", "45", "60"], correct: 1 },
    { id: 2008, level: 1, category: "klasse2", question: "Rechne aus: 50 + 50?", answers: ["80", "90", "100", "110"], correct: 2 },
    { id: 2009, level: 1, category: "klasse2", question: "Wie viel fehlt von 85 bis 100?", answers: ["5", "15", "25", "35"], correct: 1 },
    { id: 2010, level: 1, category: "klasse2", question: "Rechne aus: 4 * 5?", answers: ["15", "20", "25", "30"], correct: 1 },
    { id: 2011, level: 1, category: "klasse2", question: "Was ist 100 - 30?", answers: ["60", "70", "80", "90"], correct: 1 },
    { id: 2012, level: 1, category: "klasse2", question: "Was ist das Doppelte von 15?", answers: ["20", "25", "30", "35"], correct: 2 },
    { id: 2013, level: 1, category: "klasse2", question: "Rechne aus: 12 - 9?", answers: ["2", "3", "4", "5"], correct: 1 },
    { id: 2014, level: 1, category: "klasse2", question: "Was ergibt 3 * 10?", answers: ["13", "23", "30", "40"], correct: 2 },
    { id: 2015, level: 1, category: "klasse2", question: "Was ist die Hälfte von 14?", answers: ["6", "7", "8", "9"], correct: 1 },
    { id: 2016, level: 2, category: "klasse2", question: "Rechne aus: 36 + 15?", answers: ["41", "51", "61", "55"], correct: 1 },
    { id: 2017, level: 2, category: "klasse2", question: "Was ist 80 - 25?", answers: ["55", "65", "45", "50"], correct: 0 },
    { id: 2018, level: 2, category: "klasse2", question: "Rechne aus: 6 * 2?", answers: ["10", "12", "14", "16"], correct: 1 },
    { id: 2019, level: 2, category: "klasse2", question: "Wie viele Einer hat die Zahl 74?", answers: ["7 Einer", "4 Einer", "74 Einer", "14 Einer"], correct: 1 },
    { id: 2020, level: 2, category: "klasse2", question: "Wie viele Zehner hat die Zahl 59?", answers: ["9 Zehner", "5 Zehner", "50 Zehner", "14 Zehner"], correct: 1 },
    { id: 2021, level: 2, category: "klasse2", question: "Rechne aus: 40 + 27?", answers: ["57", "67", "77", "87"], correct: 1 },
    { id: 2022, level: 2, category: "klasse2", question: "Was ist 70 - 15?", answers: ["45", "55", "65", "50"], correct: 1 },
    { id: 2023, level: 2, category: "klasse2", question: "Rechne aus: 3 * 4?", answers: ["10", "12", "14", "16"], correct: 1 },
    { id: 2024, level: 2, category: "klasse2", question: "Rechne aus: 5 * 5?", answers: ["10", "20", "25", "30"], correct: 2 },
    { id: 2025, level: 2, category: "klasse2", question: "Was ergibt 90 - 45?", answers: ["35", "45", "55", "65"], correct: 1 },
    { id: 2026, level: 2, category: "klasse2", question: "Rechne aus: 18 + 18?", answers: ["32", "34", "36", "38"], correct: 2 },
    { id: 2027, level: 2, category: "klasse2", question: "Rechne aus: 7 * 5?", answers: ["30", "35", "40", "45"], correct: 1 },
    { id: 2028, level: 2, category: "klasse2", question: "Was ist die Hälfte von 50?", answers: ["15", "20", "25", "30"], correct: 2 },
    { id: 2029, level: 2, category: "klasse2", question: "Was ergibt 12geteilt durch 2?", answers: ["4", "5", "6", "7"], correct: 2 },
    { id: 2030, level: 2, category: "klasse2", question: "Rechne aus: 15geteilt durch 3?", answers: ["3", "4", "5", "6"], correct: 2 },
    { id: 2031, level: 2, category: "klasse2", question: "Rechne aus: 8 * 10?", answers: ["18", "80", "88", "90"], correct: 1 },
    { id: 2032, level: 2, category: "klasse2", question: "Was ergibt 100 - 55?", answers: ["35", "45", "55", "65"], correct: 1 },
    { id: 2033, level: 2, category: "klasse2", question: "Rechne aus: 49 + 7?", answers: ["54", "55", "56", "57"], correct: 2 },
    { id: 2034, level: 2, category: "klasse2", question: "Rechne aus: 63 - 8?", answers: ["53", "54", "55", "56"], correct: 2 },
    { id: 2035, level: 2, category: "klasse2", question: "Was ergibt 9 * 2?", answers: ["11", "16", "18", "20"], correct: 2 },
    { id: 2036, level: 3, category: "klasse2", question: "Rechne aus: 42 + 29?", answers: ["61", "71", "81", "72"], correct: 1 },
    { id: 2037, level: 3, category: "klasse2", question: "Rechne aus: 91 - 34?", answers: ["57", "67", "47", "53"], correct: 0 },
    { id: 2038, level: 3, category: "klasse2", question: "Was ergibt 8 * 5?", answers: ["35", "40", "45", "50"], correct: 1 },
    { id: 2039, level: 3, category: "klasse2", question: "Was ist 24geteilt durch 4?", answers: ["5", "6", "7", "8"], correct: 1 },
    { id: 2040, level: 3, category: "klasse2", question: "Was ist das Doppelte von 47?", answers: ["84", "94", "104", "96"], correct: 1 },
    { id: 2041, level: 3, category: "klasse2", question: "Rechne aus: 100 - 13?", answers: ["77", "87", "97", "83"], correct: 1 },
    { id: 2042, level: 3, category: "klasse2", question: "Was ergibt 7 * 3?", answers: ["10", "21", "24", "27"], correct: 1 },
    { id: 2043, level: 3, category: "klasse2", question: "Was ist 32geteilt durch 4?", answers: ["6", "7", "8", "9"], correct: 2 },
    { id: 2044, level: 3, category: "klasse2", question: "Was ist das Dreifache von 15?", answers: ["30", "45", "60", "75"], correct: 1 },
    { id: 2045, level: 3, category: "klasse2", question: "Rechne aus: 58 + 27?", answers: ["75", "85", "95", "83"], correct: 1 },
    { id: 2046, level: 3, category: "klasse2", question: "Rechne aus: 73 - 48?", answers: ["25", "35", "45", "33"], correct: 0 },
    { id: 2047, level: 3, category: "klasse2", question: "Was ergibt 9 * 5?", answers: ["40", "45", "50", "55"], correct: 1 },
    { id: 2048, level: 3, category: "klasse2", question: "Was ist 40geteilt durch 5?", answers: ["6", "7", "8", "9"], correct: 2 },
    { id: 2049, level: 3, category: "klasse2", question: "Rechne aus: 64 + 19?", answers: ["73", "83", "93", "81"], correct: 1 },
    { id: 2050, level: 3, category: "klasse2", question: "Rechne aus: 82 - 67?", answers: ["15", "25", "35", "13"], correct: 0 },

    // --- DEUTSCH & MÄRCHEN 2. KLASSE (IDs 2051 - 2100) ---
    { id: 2051, level: 1, category: "klasse2", question: "Welches Tier spuckte in alten Geschichten oft Feuer?", answers: ["Der Wolf", "Der Drache", "Der Bär", "Der Frosch"], correct: 1 },
    { id: 2052, level: 1, category: "klasse2", question: "In welchem Märchen schläft ein ganzes Schloss für 100 Jahre?", answers: ["Dornröschen", "Schneewittchen", "Aschenputtel", "Rapunzel"], correct: 0 },
    { id: 2053, level: 1, category: "klasse2", question: "Was ließ Rapunzel aus dem hohen Turm herunterfallen?", answers: ["Eine Strickleiter", "Ihre Haare", "Einen goldenen Ball", "Ein Seil"], correct: 1 },
    { id: 2054, level: 1, category: "klasse2", question: "Welches Tier ist 'Fleißig'?", answers: ["Die Biene", "Das Faultier", "Die Schildkröte", "Der Esel"], correct: 0 },
    { id: 2055, level: 1, category: "klasse2", question: "Wie heißt der Mann, der sehr viel Glück hatte?", answers: ["Hans im Glück", "König Umut", "Sindbad", "Ali Baba"], correct: 0 },
    { id: 2056, level: 1, category: "klasse2", question: "Was lag im Märchen 'Prinzessin auf der Erbse' unter vielen Matratzen?", answers: ["Eine Erbse", "Eine Münze", "Eine Nadel", "Eine Feder"], correct: 0 },
    { id: 2057, level: 1, category: "klasse2", question: "Wie lautet der berühmte Spruch: 'Sesam, öffne...'", answers: ["dich!", "das Tor!", "die Truhe!", "schnell!"], correct: 0 },
    { id: 2058, level: 1, category: "klasse2", question: "Wo steht der Esel auf dem Hund, der Katze und dem Hahn?", answers: ["In Hamburg", "In Berlin", "In Bremen", "In Köln"], correct: 2 },
    { id: 2059, level: 1, category: "klasse2", question: "Wie viele Räuber gab es in der Geschichte von Ali Baba?", answers: ["7 Räuber", "10 Räuber", "20 Räuber", "40 Räuber"], correct: 3 },
    { id: 2060, level: 1, category: "klasse2", question: "In welchem Märchen gibt es ein Lebkuchenhaus im Wald?", answers: ["Hänsel und Gretel", "Rotkäppchen", "Schneewittchen", "Dornröschen"], correct: 0 },
    { id: 2061, level: 1, category: "klasse2", question: "Was ist ein Wort, das sich auf 'Lachen' reimt?", answers: ["Machen", "Sachen", "Suchen", "Kuchen"], correct: 1 },
    { id: 2062, level: 1, category: "klasse2", question: "Welches Wort ist ein Nomen (Namenwort)?", answers: ["laufen", "schön", "Das Haus", "schnell"], correct: 2 },
    { id: 2063, level: 1, category: "klasse2", question: "Was ist das Gegenteil von 'fleißig'?", answers: ["nett", "faul", "stark", "klug"], correct: 1 },
    { id: 2064, level: 1, category: "klasse2", question: "Mit welchem Buchstaben fängt 'Esel' an?", answers: ["A", "E", "I", "O"], correct: 1 },
    { id: 2065, level: 1, category: "klasse2", question: "Welches Tier ist KEIN Haustier?", answers: ["Der Hund", "Die Katze", "Der Löwe", "Das Kaninchen"], correct: 2 },
    { id: 2066, level: 2, category: "klasse2", question: "Was tauscht Hans im Glück als Erstes ein?", answers: ["Seinen Goldklumpen", "Ein Pferd", "Eine Kuh", "Ein Schwein"], correct: 0 },
    { id: 2067, level: 2, category: "klasse2", question: "Welches Tier flog in den Märchen auf einem fliegenden Teppich?", answers: ["Der Löwe", "Der Falke", "Der Dieb", "Der König"], correct: 2 },
    { id: 2068, level: 2, category: "klasse2", question: "Ergänze das Wort: 'Märchen____'", answers: ["wald", "haus", "baum", "pfad"], correct: 0 },
    { id: 2069, level: 2, category: "klasse2", question: "Wie viele Zwerge leben im Wald mit Schneewittchen?", answers: ["5 Zwerge", "6 Zwerge", "7 Zwerge", "8 Zwerge"], correct: 2 },
    { id: 2070, level: 2, category: "klasse2", question: "Welcher Vogel kräht morgens auf dem Bauernhof?", answers: ["Die Ente", "Der Hahn", "Die Taube", "Der Adler"], correct: 1 },
    { id: 2071, level: 2, category: "klasse2", question: "Welches Wort reimt sich auf 'Sonne'?", answers: ["Wonne", "Mond", "Wolke", "Himmel"], correct: 0 },
    { id: 2072, level: 2, category: "klasse2", question: "Wie viele Silben hat das Wort 'Märchenpark'?", answers: ["2 Silben", "3 Silben", "4 Silben", "5 Silben"], correct: 1 },
    { id: 2073, level: 2, category: "klasse2", question: "Welches Wort ist ein Verb (Tunwort)?", answers: ["Groß", "Singen", "Katze", "Schön"], correct: 1 },
    { id: 2074, level: 2, category: "klasse2", question: "Wer schläft im Wald und wurde von Schneewittchen besucht?", answers: ["Die Riesen", "Die Zwerge", "Die Feen", "Die Drachen"], correct: 1 },
    { id: 2075, level: 2, category: "klasse2", question: "Welches Tier ist sehr langsam?", answers: ["Die Schnecke", "Der Hase", "Der Hund", "Das Pferd"], correct: 0 },
    { id: 2076, level: 2, category: "klasse2", question: "Was ist das Gegenteil von 'heiß'?", answers: ["warm", "kalt", "trocken", "nass"], correct: 1 },
    { id: 2077, level: 2, category: "klasse2", question: "Was glänzt oft golden im Märchen?", answers: ["Münzen", "Blätter", "Bäume", "Steine"], correct: 0 },
    { id: 2078, level: 2, category: "klasse2", question: "Wer reist in Geschichten oft auf dem Meer und erlebt Abenteuer?", answers: ["Sindbad", "König Umut", "Rotkäppchen", "Schneewittchen"], correct: 0 },
    { id: 2079, level: 2, category: "klasse2", question: "Welches Tier ist berühmt für seine langen Ohren?", answers: ["Der Hase", "Die Maus", "Die Katze", "Der Hund"], correct: 0 },
    { id: 2080, level: 2, category: "klasse2", question: "Was isst die Prinzessin im Märchen gerne, das 'süß' schmeckt?", answers: ["Zitronen", "Zuckerwatte", "Salzstangen", "Kartoffeln"], correct: 1 },
    { id: 2081, level: 2, category: "klasse2", question: "Welcher Buchstabe fehlt in: 'K_tze'?", answers: ["a", "e", "o", "u"], correct: 0 },
    { id: 2082, level: 2, category: "klasse2", question: "Welches Wort beschreibt ein sehr großes Wesen im Märchen?", answers: ["Zwerg", "Riese", "Prinz", "Elfe"], correct: 1 },
    { id: 2083, level: 2, category: "klasse2", question: "Was ist das Gegenteil von 'groß'?", answers: ["riesig", "breit", "klein", "hoch"], correct: 2 },
    { id: 2084, level: 2, category: "klasse2", question: "Wie schreibt man das Wort 'Schule' richtig?", answers: ["Schuhle", "Schule", "Shule", "Tschule"], correct: 1 },
    { id: 2085, level: 2, category: "klasse2", question: "Welches Tier summt auf der Wiese?", answers: ["Die Fliege", "Die Biene", "Der Wurm", "Der Käfer"], correct: 1 },
    { id: 2086, level: 3, category: "klasse2", question: "Welches Wort reimt sich auf 'Zauberschloss'?", answers: ["Kopfnuss", "Riesenross", "Wasserfluss", "Zuckerguss"], correct: 1 },
    { id: 2087, level: 3, category: "klasse2", question: "Wie nennt man ein Wort, das eine Eigenschaft beschreibt?", answers: ["Nomen", "Verb", "Adjektiv", "Artikel"], correct: 2 },
    { id: 2088, level: 3, category: "klasse2", question: "Was bedeutet das Wort 'Umut' übersetzt?", answers: ["Liebe", "Glück", "Hoffnung", "Frieden"], correct: 2 },
    { id: 2089, level: 3, category: "klasse2", question: "Welches Märchentier überlistete den großen, bösen Wolf?", answers: ["Die sieben Geißlein", "Dornröschen", "Die Prinzessin", "Der Esel"], correct: 0 },
    { id: 2090, level: 3, category: "klasse2", question: "Wie viele Selbstlaute (Vokale) hat das Wort 'Dornröschen'?", answers: ["3 Vokale", "4 Vokale", "5 Vokale", "6 Vokale"], correct: 1 },
    { id: 2091, level: 3, category: "klasse2", question: "Welches Satzzeichen gehört am Ende einer Frage?", answers: ["Punkt", "Ausrufezeichen", "Fragezeichen", "Komma"], correct: 2 },
    { id: 2092, level: 3, category: "klasse2", question: "Welches Wort ist richtig getrennt?", answers: ["Mär-chen", "Mä-rchen", "Märc-hen", "M-ärchen"], correct: 0 },
    { id: 2093, level: 3, category: "klasse2", question: "Welcher Artikel gehört zu 'Zauberstab'?", answers: ["die", "das", "der", "einem"], correct: 2 },
    { id: 2094, level: 3, category: "klasse2", question: "Welches Wort ist ein Adjektiv (Wiewort)?", answers: ["schreiben", "schnell", "Stift", "Tisch"], correct: 1 },
    { id: 2095, level: 3, category: "klasse2", question: "Wie lautet die Mehrzahl von 'Märchenbuch'?", answers: ["Märchenbuche", "Märchenbücher", "Märchenbuchs", "Märchenbüchern"], correct: 1 },
    { id: 2096, level: 3, category: "klasse2", question: "Welches Tier ist für seine Schlauheit im Märchen bekannt?", answers: ["Der Bär", "Der Esel", "Der Fuchs", "Der Wolf"], correct: 2 },
    { id: 2097, level: 3, category: "klasse2", question: "Was ist das Gegenteil von 'reich'?", answers: ["arm", "schwach", "traurig", "schlecht"], correct: 0 },
    { id: 2098, level: 3, category: "klasse2", question: "Welcher Buchstabe ist ein Umlaut?", answers: ["A", "E", "Ö", "U"], correct: 2 },
    { id: 2099, level: 3, category: "klasse2", question: "Wie nennt man die Hauptfigur in 'Prinzessin auf der Erbse'?", answers: ["Prinzessin", "Königin", "Ritter", "Zwerg"], correct: 0 },
    { id: 2100, level: 3, category: "klasse2", question: "Welches Wort reimt sich auf 'Süß'?", answers: ["Fuß", "Nuss", "Kuss", "Fluss"], correct: 0 },


    // ==========================================
    // KATEGORIE: KLASSE 5 (100 FRAGEN)
    // ==========================================
    
    // --- ENGLISCH 5. KLASSE (IDs 5001 - 5100) ---
    { id: 5001, level: 1, category: "klasse5", question: "What is the correct answer to: 'Hello, what is your name?'", answers: ["I am ten years old.", "My name is Sarah.", "I am a boy.", "Fine, thanks."], correct: 1 },
    { id: 5002, level: 1, category: "klasse5", question: "Which number is 'fifteen'?", answers: ["5", "15", "50", "115"], correct: 1 },
    { id: 5003, level: 1, category: "klasse5", question: "What colour do you get when you mix blue and yellow?", answers: ["red", "purple", "green", "orange"], correct: 2 },
    { id: 5004, level: 1, category: "klasse5", question: "Translate to English: 'Klassenzimmer'", answers: ["classroom", "schoolbag", "playground", "teacherroom"], correct: 0 },
    { id: 5005, level: 1, category: "klasse5", question: "Where do wild animals live in a city?", answers: ["at school", "at the zoo", "at home", "in the garden"], correct: 1 },
    { id: 5006, level: 1, category: "klasse5", question: "Which pet is known for saying 'Meow'?", answers: ["dog", "cat", "rabbit", "hamster"], correct: 1 },
    { id: 5007, level: 1, category: "klasse5", question: "What do you wear when it is cold outside?", answers: ["shorts", "a T-shirt", "a warm coat", "swimwear"], correct: 2 },
    { id: 5008, level: 1, category: "klasse5", question: "What is the English word for 'Regen'?", answers: ["sun", "snow", "rain", "wind"], correct: 2 },
    { id: 5009, level: 1, category: "klasse5", question: "Which animal lives on a farm and gives milk?", answers: ["pig", "cow", "chicken", "sheep"], correct: 1 },
    { id: 5010, level: 1, category: "klasse5", question: "Which body part do you use to hear music?", answers: ["eyes", "ears", "nose", "mouth"], correct: 1 },
    { id: 5011, level: 1, category: "klasse5", question: "What fruit is red and very popular?", answers: ["banana", "apple", "cucumber", "potato"], correct: 1 },
    { id: 5012, level: 1, category: "klasse5", question: "What do you usually drink for breakfast?", answers: ["pizza", "soup", "milk", "pasta"], correct: 2 },
    { id: 5013, level: 1, category: "klasse5", question: "Translate: 'Meine Familie'", answers: ["my friends", "my school", "my family", "my home"], correct: 2 },
    { id: 5014, level: 1, category: "klasse5", question: "What is the name of the big holiday in December?", answers: ["Easter", "Halloween", "Christmas", "Summer holiday"], correct: 2 },
    { id: 5015, level: 1, category: "klasse5", question: "Which of these is a number?", answers: ["green", "seven", "school", "pencil"], correct: 1 },
    { id: 5016, level: 1, category: "klasse5", question: "What is the opposite of 'big'?", answers: ["small", "tall", "long", "heavy"], correct: 0 },
    { id: 5017, level: 1, category: "klasse5", question: "What do you write with at school?", answers: ["rubber", "ruler", "pencil", "book"], correct: 2 },
    { id: 5018, level: 1, category: "klasse5", question: "Which animal is very tall and has a long neck?", answers: ["elephant", "giraffe", "monkey", "lion"], correct: 1 },
    { id: 5019, level: 1, category: "klasse5", question: "What is 'Guten Morgen' in English?", answers: ["Good afternoon", "Good evening", "Good morning", "Good night"], correct: 2 },
    { id: 5020, level: 1, category: "klasse5", question: "Complete the sentence: 'I ___ ten years old.'", answers: ["is", "am", "are", "have"], correct: 1 },
    { id: 5021, level: 1, category: "klasse5", question: "Which colour is the sky on a sunny day?", answers: ["yellow", "green", "blue", "grey"], correct: 2 },
    { id: 5022, level: 1, category: "klasse5", question: "What do you use to erase pencil lines?", answers: ["ruler", "rubber", "sharpener", "scissors"], correct: 1 },
    { id: 5023, level: 1, category: "klasse5", question: "What animal has wings and can fly?", answers: ["fish", "bird", "frog", "tiger"], correct: 1 },
    { id: 5024, level: 1, category: "klasse5", question: "What is 'Hund' in English?", answers: ["cat", "cow", "dog", "horse"], correct: 2 },
    { id: 5025, level: 1, category: "klasse5", question: "What clothes do you wear on your feet?", answers: ["hat", "socks", "gloves", "scarf"], correct: 1 },
    { id: 5026, level: 1, category: "klasse5", question: "What do we call a very strong wind with rain?", answers: ["sunny day", "storm", "snow", "warm wave"], correct: 1 },
    { id: 5027, level: 1, category: "klasse5", question: "Which farm animal clucks and lays eggs?", answers: ["chicken", "sheep", "horse", "pig"], correct: 0 },
    { id: 5028, level: 1, category: "klasse5", question: "How many fingers do you have on one hand?", answers: ["four", "five", "ten", "eight"], correct: 1 },
    { id: 5029, level: 1, category: "klasse5", question: "Which vegetable is orange and good for your eyes?", answers: ["potato", "tomato", "carrot", "onion"], correct: 2 },
    { id: 5030, level: 1, category: "klasse5", question: "What is 'Wasser' in English?", answers: ["juice", "milk", "tea", "water"], correct: 3 },
    { id: 5031, level: 1, category: "klasse5", question: "Who is the mother of your father?", answers: ["mother", "sister", "grandmother", "aunt"], correct: 2 },
    { id: 5032, level: 1, category: "klasse5", question: "What do people put under the Christmas tree?", answers: ["schoolbags", "presents", "fruits", "clothes"], correct: 1 },
    { id: 5033, level: 1, category: "klasse5", question: "Which number is 'twelve'?", answers: ["2", "12", "20", "22"], correct: 1 },
    { id: 5034, level: 1, category: "klasse5", question: "What colour is a banana?", answers: ["red", "blue", "yellow", "green"], correct: 2 },
    { id: 5035, level: 1, category: "klasse5", question: "What do you use to carry your schoolbooks?", answers: ["pencil case", "schoolbag", "lunchbox", "pocket"], correct: 1 },
    { id: 5036, level: 2, category: "klasse5", question: "Translate: 'Wie alt bist du?'", answers: ["How are you?", "How old are you?", "Who are you?", "What is your name?"], correct: 1 },
    { id: 5037, level: 2, category: "klasse5", question: "Count in steps: 'ten, twenty, thirty, ___'", answers: ["thirty-one", "forty", "fifty", "sixty"], correct: 1 },
    { id: 5038, level: 2, category: "klasse5", question: "Which word means 'Lieblingsfarbe'?", answers: ["favorite pet", "favorite colour", "favorite food", "favorite school subject"], correct: 1 },
    { id: 5039, level: 2, category: "klasse5", question: "Complete: 'Can I have your rubber, ___?'", answers: ["thank you", "please", "sorry", "welcome"], correct: 1 },
    { id: 5040, level: 2, category: "klasse5", question: "What do monkeys love to eat?", answers: ["meat", "bananas", "potatoes", "bread"], correct: 1 },
    { id: 5041, level: 2, category: "klasse5", question: "Translate: 'Ich habe ein Meerschweinchen.'", answers: ["I have a mouse.", "I have a guinea pig.", "I have a hamster.", "I have a rabbit."], correct: 1 },
    { id: 5042, level: 2, category: "klasse5", question: "What do you put on before you put on your shoes?", answers: ["trousers", "socks", "hat", "jacket"], correct: 1 },
    { id: 5043, level: 2, category: "klasse5", question: "What is the English word for 'Schnee'?", answers: ["cloud", "wind", "snow", "fog"], correct: 2 },
    { id: 5044, level: 2, category: "klasse5", question: "Which animal says 'Oink'?", answers: ["cow", "sheep", "pig", "horse"], correct: 2 },
    { id: 5045, level: 2, category: "klasse5", question: "What are 'shoulders' in German?", answers: ["Knie", "Schultern", "Ellbogen", "Hände"], correct: 1 },
    { id: 5046, level: 2, category: "klasse5", question: "Translate: 'Erdbeere'", answers: ["strawberry", "apple", "lemon", "pear"], correct: 0 },
    { id: 5047, level: 2, category: "klasse5", question: "What do you call the first meal of the day?", answers: ["lunch", "dinner", "breakfast", "supper"], correct: 2 },
    { id: 5048, level: 2, category: "klasse5", question: "Who is the brother of your mother?", answers: ["uncle", "aunt", "cousin", "grandfather"], correct: 0 },
    { id: 5049, level: 2, category: "klasse5", question: "What is the English word for 'Rentier'?", answers: ["deer", "reindeer", "horse", "donkey"], correct: 1 },
    { id: 5050, level: 2, category: "klasse5", question: "How do you say 'fünfzig' in English?", answers: ["fifteen", "five", "fifty", "five-hundred"], correct: 2 },
    { id: 5051, level: 2, category: "klasse5", question: "Which color do you get when you mix red and white?", answers: ["pink", "orange", "purple", "brown"], correct: 0 },
    { id: 5052, level: 2, category: "klasse5", question: "Where does a teacher write on with chalk?", answers: ["paper", "blackboard", "desk", "window"], correct: 1 },
    { id: 5053, level: 2, category: "klasse5", question: "What is the king of the jungle?", answers: ["tiger", "lion", "elephant", "bear"], correct: 1 },
    { id: 5054, level: 2, category: "klasse5", question: "Translate: 'Ich mag Hunde.'", answers: ["I have a dog.", "I like dogs.", "Dogs are big.", "My dog is friendly."], correct: 1 },
    { id: 5055, level: 2, category: "klasse5", question: "What is 'Jacke' in English?", answers: ["trousers", "jacket", "shirt", "shoes"], correct: 1 },
    { id: 5056, level: 2, category: "klasse5", question: "Which season comes after winter?", answers: ["summer", "autumn", "spring", "christmas"], correct: 2 },
    { id: 5057, level: 2, category: "klasse5", question: "What noise does a sheep make?", answers: ["oink", "moo", "baa", "woof"], correct: 2 },
    { id: 5058, level: 2, category: "klasse5", question: "What is 'Knie' in English?", answers: ["elbow", "knee", "finger", "toe"], correct: 1 },
    { id: 5059, level: 2, category: "klasse5", question: "What is 'Zitrone' in English?", answers: ["orange", "lemon", "grape", "melon"], correct: 1 },
    { id: 5060, level: 2, category: "klasse5", question: "Which drink comes from oranges?", answers: ["milk", "apple juice", "orange juice", "water"], correct: 2 },
    { id: 5061, level: 2, category: "klasse5", question: "Who is your aunt's son?", answers: ["brother", "uncle", "cousin", "nephew"], correct: 2 },
    { id: 5062, level: 2, category: "klasse5", question: "Which month is Christmas in?", answers: ["November", "December", "January", "October"], correct: 1 },
    { id: 5063, level: 2, category: "klasse5", question: "How do you write 'einhundert'?", answers: ["ten", "one thousand", "one hundred", "one million"], correct: 2 },
    { id: 5064, level: 2, category: "klasse5", question: "Which colour is a flamingo?", answers: ["yellow", "pink", "blue", "black"], correct: 1 },
    { id: 5065, level: 2, category: "klasse5", question: "What do you use to sharpen a pencil?", answers: ["scissors", "sharpener", "ruler", "pencil case"], correct: 1 },
    { id: 5066, level: 3, category: "klasse5", question: "Complete: 'Where ___ my schoolbags?'", answers: ["is", "am", "are", "have"], correct: 2 },
    { id: 5067, level: 3, category: "klasse5", question: "What is the English word for 'Schildkröte'?", answers: ["snake", "turtle", "lizard", "frog"], correct: 1 },
    { id: 5068, level: 3, category: "klasse5", question: "Translate: 'Zieh deine Jacke an!'", answers: ["Take off your jacket!", "Put on your jacket!", "Where is your jacket?", "Your jacket is warm."], correct: 1 },
    { id: 5069, level: 3, category: "klasse5", question: "What do we call frozen rain falling from the sky?", answers: ["hail", "fog", "storm", "sunshine"], correct: 0 },
    { id: 5070, level: 3, category: "klasse5", question: "Translate: 'Esel' to English", answers: ["horse", "donkey", "goat", "sheep"], correct: 1 },
    { id: 5071, level: 3, category: "klasse5", question: "Which word describes how you feel when you are very tired?", answers: ["happy", "sleepy", "angry", "scared"], correct: 1 },
    { id: 5072, level: 3, category: "klasse5", question: "What is the English term for 'Trauben'?", answers: ["berries", "pears", "grapes", "cherries"], correct: 2 },
    { id: 5073, level: 3, category: "klasse5", question: "What is the meal you eat in the evening?", answers: ["breakfast", "lunch", "dinner", "snack"], correct: 2 },
    { id: 5074, level: 3, category: "klasse5", question: "Translate: 'Geschwister'", answers: ["parents", "siblings", "cousins", "grandparents"], correct: 1 },
    { id: 5075, level: 3, category: "klasse5", question: "What is the day before Christmas Day (24th December) called?", answers: ["Boxing Day", "Christmas Eve", "New Year's Eve", "Thanksgiving"], correct: 1 },
    { id: 5076, level: 3, category: "klasse5", question: "Write 'dreihundertvierundfünfzig' in numbers:", answers: ["345", "354", "534", "435"], correct: 1 },
    { id: 5077, level: 3, category: "klasse5", question: "Translate: 'Schreibmäppchen'", answers: ["pencil case", "schoolbag", "notebook", "folder"], correct: 0 },
    { id: 5078, level: 3, category: "klasse5", question: "Which of these is a reptile?", answers: ["tiger", "eagle", "crocodile", "frog"], correct: 2 },
    { id: 5079, level: 3, category: "klasse5", question: "What is 'Zahn' in English (singular)?", answers: ["tooth", "teeth", "foot", "feet"], correct: 0 },
    { id: 5080, level: 3, category: "klasse5", question: "What is 'Pfirsich' in English?", answers: ["peach", "plum", "cherry", "pear"], correct: 0 },
    { id: 5081, level: 3, category: "klasse5", question: "What does 'Are you fine?' mean?", answers: ["Bist du klein?", "Geht es dir gut?", "Bist du fertig?", "Wer bist du?"], correct: 1 },
    { id: 5082, level: 3, category: "klasse5", question: "What is the English word for 'Augenbrauen'?", answers: ["eyebrows", "eyelashes", "forehead", "cheeks"], correct: 0 },
    { id: 5083, level: 3, category: "klasse5", question: "Translate: 'Schere'", answers: ["ruler", "scissors", "glue", "paper"], correct: 1 },
    { id: 5084, level: 3, category: "klasse5", question: "Which animal is slow and has a shell?", answers: ["snail", "crab", "lizard", "rabbit"], correct: 0 },
    { id: 5085, level: 3, category: "klasse5", question: "Translate: 'Zieh deine Schuhe aus!'", answers: ["Put on your shoes!", "Take off your shoes!", "Find your shoes!", "Clean your shoes!"], correct: 1 },
    { id: 5086, level: 3, category: "klasse5", question: "What is 'Nebel' in English?", answers: ["fog", "cloud", "rain", "wind"], correct: 0 },
    { id: 5087, level: 3, category: "klasse5", question: "What do we call a baby cow?", answers: ["calf", "lamb", "foal", "piglet"], correct: 0 },
    { id: 5088, level: 3, category: "klasse5", question: "What is 'Zunge' in English?", answers: ["mouth", "tongue", "lip", "tooth"], correct: 1 },
    { id: 5089, level: 3, category: "klasse5", question: "What is 'Knoblauch' in English?", answers: ["garlic", "onion", "ginger", "pepper"], correct: 0 },
    { id: 5090, level: 3, category: "klasse5", question: "What is 'Essig' in English?", answers: ["oil", "vinegar", "salt", "sauce"], correct: 1 },
    { id: 5091, level: 3, category: "klasse5", question: "Who is your father's sister?", answers: ["aunt", "uncle", "mother", "cousin"], correct: 0 },
    { id: 5092, level: 3, category: "klasse5", question: "Which plant is typical for Christmas?", answers: ["sunflower", "holly", "rose", "tulip"], correct: 1 },
    { id: 5093, level: 3, category: "klasse5", question: "How do you write 'achtundachtzig' in English?", answers: ["eighty-eight", "eighteen", "eighty", "eighty-eighty"], correct: 0 },
    { id: 5094, level: 3, category: "klasse5", question: "What do you say if you did something wrong?", answers: ["Please", "Excuse me", "I am sorry", "Thank you"], correct: 2 },
    { id: 5095, level: 3, category: "klasse5", question: "What is the English name for 'Weißkohl'?", answers: ["cabbage", "lettuce", "spinach", "broccoli"], correct: 0 },
    { id: 5096, level: 3, category: "klasse5", question: "What is 'Gürtel' in English?", answers: ["belt", "scarf", "glove", "socks"], correct: 0 },
    { id: 5097, level: 3, category: "klasse5", question: "Which bird is active at night?", answers: ["eagle", "owl", "parrot", "sparrow"], correct: 1 },
    { id: 5098, level: 3, category: "klasse5", question: "What is the English word for 'Kinn'?", answers: ["cheek", "chin", "forehead", "neck"], correct: 1 },
    { id: 5099, level: 3, category: "klasse5", question: "What is the typical meat eaten on Thanksgiving?", answers: ["chicken", "turkey", "beef", "pork"], correct: 1 },
    { id: 5100, level: 3, category: "klasse5", question: "How do you write 'neunhundertneunundneunzig' in numbers?", answers: ["909", "990", "999", "9099"], correct: 2 }
];